# Generated by Django 3.2 on 2021-04-19 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('player_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_name', models.TextField()),
                ('team_location', models.TextField()),
                ('stadium', models.TextField()),
                ('sponsored', models.BooleanField()),
                ('cap_space', models.IntegerField()),
                ('capital', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('pass_word', models.TextField()),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.team')),
            ],
        ),
    ]
