# Generated by Django 3.2 on 2021-04-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
        migrations.RenameModel(
            old_name='Trades',
            new_name='Trade',
        ),
    ]
