# Generated by Django 3.2 on 2021-04-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_auto_20210419_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
